package com.example.ui.screens

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

object L {
    var currentLang by mutableStateOf("English") // "English" or "Hindi"

    // Translation dictionary mapping English text to Hindi equivalents
    private val translations = mapOf(
        "Dashboard" to "डैशबोर्ड",
        "Collection" to "दूध संग्रह",
        "Farmers" to "किसान सूची",
        "Products" to "उत्पाद स्टॉक",
        "POS Sales" to "बिक्री (POS)",
        "Payments" to "भुगतान",
        "Expenses" to "खर्चे",
        "Reports" to "रिपोर्ट्स",
        "Settings" to "सेटिंग्स",
        "Home" to "मुख्य पृष्ठ",
        "Collect" to "संग्रह",
        "Sales" to "बिक्री",
        "Farmers" to "किसान",
        "SaaS Preferences" to "डेयरीHub प्राथमिकताएं",
        "Language Preference" to "भाषा (Language)",
        "Dark Mode" to "डार्क थीम",
        "App Lock" to "सुरक्षा ऐप लॉक",
        "Printer Configuration" to "प्रिंटर सेटिंग्स",
        "SMS Settings" to "एसएमएस गेटवे",
        "WhatsApp Settings" to "व्हाट्सएप सेटिंग्स",
        "Center Name" to "डेयरी केंद्र का नाम",
        "Center Code" to "केंद्र कोड (MCC)",
        "Save Settings" to "सेटिंग्स सुरक्षित करें",
        "English" to "English (अंग्रेजी)",
        "Hindi" to "हिन्दी (Hindi)",
        "Milk Collection Form" to "दूध संग्रह प्रविष्टि",
        "Farmer / Supplier" to "आपूर्तिकर्ता किसान",
        "Shift" to "पारी (Shift)",
        "Morning" to "सुबह (Morning)",
        "Evening" to "शाम (Evening)",
        "Milk Type" to "दूध का प्रकार",
        "Cow" to "गाय (Cow)",
        "Buffalo" to "भैंस (Buffalo)",
        "Quantity (Ltr)" to "मात्रा (लीटर)",
        "FAT (%)" to "फैट (FAT %)",
        "SNF (%)" to "एसएनएफ (SNF %)",
        "CLR Reading" to "सीएलआर (CLR)",
        "Calculated Rate" to "दूध दर (₹/L)",
        "Total Amount" to "कुल देय राशि (₹)",
        "Submit Collection" to "संग्रह सुरक्षित करें",
        "Duplicate Warning" to "दोहरी प्रविष्टि चेतावनी",
        "Recent Collections" to "आज का हालिया संग्रह",
        "New Sale POS" to "सामग्री बिक्री काउंटर",
        "Sales History" to "बिक्री लॉग इतिहास",
        "SaaS Interactive POS Terminal" to "एसएएएस बिक्री टर्मिनल",
        "Buyer Portfolio" to "ग्राहक / खरीदार",
        "Walk-in Cash Customer" to "नकद काउंटर ग्राहक",
        "Add Item" to "सामग्री जोड़ें",
        "Discount" to "छूट (Discount ₹)",
        "Grand Total" to "कुल देय राशि",
        "Checkout" to "भुगतान और बिलिंग",
        "Digital Receipt" to "डिजिटल रसीद",
        "Farmers & Buyers Directory" to "किसान और ग्राहक बहीखाता",
        "Active" to "सक्रिय",
        "Inactive" to "निष्क्रिय",
        "Balance" to "बकाया शेष",
        "Add Customer" to "नया ग्राहक/किसान जोड़ें",
        "Edit Customer" to "विवरण संपादित करें",
        "Delete Customer" to "खाता हटाएं",
        "Name" to "पूरा नाम",
        "Mobile" to "मोबाइल नंबर",
        "Address" to "स्थायी पता",
        "Opening Balance" to "शुरुआती बकाया राशि",
        "Customer Type" to "खाता प्रकार (Type)",
        "Payment Mode" to "भुगतान माध्यम (Mode)",
        "Bank Name" to "बैंक का नाम",
        "Account Number" to "खाता संख्या",
        "IFSC Code" to "आईएफएससी कोड",
        "Save" to "सुरक्षित करें",
        "Cancel" to "रद्द करें",
        "Rate Chart" to "रेट चार्ट (Rate Chart)",
        "Rate Chart Module" to "दूध दर रेट चार्ट",
        "Cow Rate Chart" to "गाय दूध रेट चार्ट",
        "Buffalo Rate Chart" to "भैंस दूध रेट चार्ट",
        "FAT/SNF based Rate" to "फैट / एसएनएफ दर संरचना",
        "Manual Add Rate" to "मैन्युअल दर एंट्री",
        "Excel Upload" to "एक्सेल शीट अपलोड",
        "Download Template" to "एक्सेल टेम्प्लेट डाउनलोड",
        "Export Excel" to "एक्सेल में डाउनलोड",
        "FAT Required" to "फैट वैल्यू आवश्यक है",
        "SNF Required" to "एसएनएफ वैल्यू आवश्यक है",
        "Rate Required" to "दर वैल्यू आवश्यक है",
        "Milk Type Required" to "दूध का प्रकार आवश्यक है",
        "Invoices" to "इनवॉइस और रसीद",
        "Invoices & Receipts Hub" to "इनवॉइस और रसीद हब",
        "Collection Invoice" to "संग्रह इनवॉइस",
        "Sale Invoice" to "सामग्री बिक्री इनवॉइस",
        "Farmer Payment Invoice" to "किसान भुगतान रसीद",
        "Customer Sale Invoice" to "ग्राहक बिक्री रसीद",
        "Invoice List" to "इनवॉइस बहीखाता सूची",
        "Invoice Details" to "इनवॉइस विवरण",
        "Print Invoice" to "इनवॉइस प्रिंट करें",
        "Download PDF" to "पीडीएफ डाउनलोड",
        "Share on WhatsApp" to "व्हाट्सएप पर शेयर करें",
        "Send by email" to "ईमेल पर भेजें",
        "Select language" to "भाषा का चयन करें",
        "Select Printer" to "ब्लूटूथ प्रिंटर चुनें",
        "Printer Settings" to "थर्मल प्रिंटर सेटिंग्स",
        "Printer Size" to "कागज का आकार (Paper Size)",
        "Bluetooth Printer" to "ब्लूटूथ प्रिंटर",
        "Test Print" to "टेस्ट प्रिंट रसीद",
        "Connect Printer" to "प्रिंटर कनेक्ट करें",
        "Not Connected" to "डिस्कनेक्टेड है",
        "Connected" to "सफलतापूर्वक कनेक्टेड",
        "Disconnect" to "डिसकनेक्ट करें",
        "Print" to "प्रिंट",
        "Ledger / Khata" to "ग्राहक खाता खतौनी Ledger",
        "Opening dues" to "प्रारंभिक शेष बकाया",
        "Customer ledger updated successfully" to "ग्राहक बही खाता अपडेट कर दिया गया है",
        "No records found" to "कोई डेटा नहीं मिला",
        "Search" to "खोजें...",
        "Print Success" to "सफलतापूर्वक प्रिंट किया गया",
        "Select Customer" to "ग्राहक का चयन करें",
        "Walk-in Cash Customer (Standard Counter)" to "नकद काउंटर ग्राहक (सामान्य)",
        "SaaS Interactive POS Terminal" to "एसएएएस डिजिटल पीओएस टर्मिनल",
        "Deduct inventory and update farmer accounts automatically on checkout." to "चेकआउट करने पर स्टॉक कम करें और ग्राहक खाते को स्वचालित रूप से अपडेट करें।",
        "Enter Farmer Mobile" to "किसान मोबाइल नंबर",
        "Farmer Details" to "किसान का विवरण",
        "Today's Shift Summaries" to "आज का पारी सारांश",
        "Recent Collections Log" to "हालिया दूध संग्रह लॉग",
        "Registered Farmers" to "पंजीकृत दूध उत्पादक किसान",
        "Manage Profiles" to "प्रोफाइल और खाता बही",
        "Product Catalog Inventory" to "डेयरी सामग्री एवं स्टॉक",
        "Payments & Cash Outflow" to "किसान भुगतान बहीखाता",
        "Manage Center Expenses" to "डेयरी केंद्र के खर्चे",
        "Dairy Interactive Dashboard" to "डेयरीHub डैशबोर्ड सारांश",
        "Quick Actions Panel" to "त्वरित कार्रवाई पैनल",
        "Quick Collect" to "दूध संग्रह",
        "Quick POS Sale" to "सामग्री बिक्री",
        "Receive Payment" to "भुगतान रसीद",
        "Record Expense" to "खर्चा जोड़ें",
        "Analytics Reports" to "विस्तृत रिपोर्ट",
        "Daily Operations" to "दैनिक संचालन",
        "Financial Insights" to "वित्तीय जानकारी",
        "Stock Inventory Status" to "उत्पाद स्टॉक स्थिति",
        "System Audit Log" to "सिस्टम ऑडिट लॉग",
        "Farmers Ledger" to "किसान खाता बही",
        "Customers Ledger" to "ग्राहक खाता बही Ledger",
        "Rate Chart Management" to "रेट चार्ट Management",
        "Invoices Hub" to "डिजिटल बिल इनवॉइस Hub",
        "Select supplying farmer..." to "दूध देने वाले किसान का चयन करें...",
        "Farmer / Supplier" to "किसान / आपूर्तिकर्ता",
        "Tap to select supplying farmer..." to "किसान चुनने के लिए क्लिक करें...",
        "Enter quantity in Litres" to "लीटर में मात्रा दर्ज करें",
        "Enter Fat %" to "फैट % दर्ज करें",
        "Enter SNF %" to "एसएनएफ % दर्ज करें",
        "Enter CLR" to "CLR रीडिंग दर्ज करें",
        "Selected Customer" to "चयनित ग्राहक/किसान",
        "Payment Mode" to "भुगतान प्रकार",
        "Tax Invoice Generated" to "टैक्स इनवॉइस सफलतापूर्वक बनाया गया",
        "Sales Invoice has been successfully committed to offline Room schema." to "बिक्री इनवॉइस सफलतापूर्वक स्थानीय डेटाबेस में सुरक्षित किया गया है।",
        "Print Receipt" to "रसीद प्रिंट करें",
        "Close" to "बंद करें",
        "Digital receipt contains dynamic signature. Compatible with Android printers." to "डिजिटल रसीद में डायनामिक सिग्नेचर है। यह एंड्रॉइड प्रिंटर के अनुकूल है।",
        "Farmer" to "किसान (Farmer)",
        "Retailer" to "खुदरा विक्रेता (Retailer)",
        "Wholesaler" to "थोक विक्रेता (Wholesaler)",
        "Staff" to "कर्मचारी (Staff)",
        "Cash" to "नकद (Cash)",
        "UPI" to "UPI (डिजिटल)",
        "Credit" to "उधार (Credit)",
        "Bank Transfer" to "बैंक ट्रांसफर",
        "Code" to "कोड",
        "First Name" to "पहला नाम",
        "Last Name" to "अंतिम नाम",
        "Login" to "लॉगिन करें",
        "Register" to "नया खाता बनाएं",
        "Username" to "उपयोगकर्ता नाम",
        "Password" to "पासवर्ड",
        "Full Name" to "पूरा नाम",
        "Phone" to "फ़ोन नंबर",
        "Email" to "ईमेल",
        "Role" to "भूमिका (Role)",
        "Remember Me" to "मुझे याद रखें",
        "Don't have an account? Register" to "खाता नहीं है? रजिस्टर करें",
        "Already have an account? Login" to "पहले से खाता है? लॉगिन करें",
        "Forgot Password?" to "पासवर्ड भूल गए?",
        "Log In Securely" to "सुरक्षित लॉगिन करें",
        "Register Enterprise Account" to "नया एंटरप्राइज़ खाता बनाएं",
        "New to DairyHub? Create an owner account" to "डेयरीHub में नए हैं? मालिक खाता बनाएं",
        "Have an account? Log in" to "पहले से खाता है? लॉगिन करें",
        "Enter OTP Verification Code" to "OTP सत्यापन कोड दर्ज करें",
        "A temporary security OTP has been dispatched to your registered endpoint." to "आपके पंजीकृत नंबर/ईमेल पर एक अस्थायी OTP भेजा गया है।",
        "6-Digit OTP Code" to "6-अंकों का OTP कोड",
        "Verify Security OTP" to "OTP सत्यापित करें",
        "Back to Login" to "लॉगिन पर वापस जाएं"
    )

    fun t(englishText: String): String {
        val trimmed = englishText.trim()
        val lang = currentLang.lowercase()
        if (lang.contains("hindi") || lang.contains("हिन्दी") || lang.contains("हिंदी")) {
            return translations[trimmed] ?: translations[englishText] ?: englishText
        }
        if (lang.contains("punjabi") || lang.contains("ਪੰਜਾਬੀ")) {
            return punjabiTranslations[trimmed] ?: punjabiTranslations[englishText] ?: englishText
        }
        if (lang.contains("marathi") || lang.contains("मराठी")) {
            return marathiTranslations[trimmed] ?: marathiTranslations[englishText] ?: englishText
        }
        return englishText
    }

    // Hoisted to top-level (private vals below) instead of being rebuilt inside t() on
    // every single call — t() runs hundreds of times per recomposition, so recreating
    // these maps each time was a real, avoidable performance cost.
    private val punjabiTranslations = mapOf(
        "Dashboard" to "ਡੈਸ਼ਬੋਰਡ",
        "Collection" to "ਦੁੱਧ ਸੰਗ੍ਰਹਿ",
        "Farmers" to "ਕਿਸਾਨ",
        "Products" to "ਉਤਪਾਦ",
        "POS Sales" to "ਵਿਕਰੀ",
        "Payments" to "ਭੁਗਤਾਨ",
        "Expenses" to "ਖਰਚੇ",
        "Reports" to "ਰਿਪੋਰਟਾਂ",
        "Settings" to "ਸੈਟਿੰਗਾਂ",
        "Home" to "ਮੁੱਖ ਪੰਨਾ",
        "Collect" to "ਦੁੱਧ ਇਕੱਠਾ ਕਰੋ",
        "Sales" to "ਵਿਕਰੀ",
        "Language Preference" to "ਭਾਸ਼ਾ ਚੋਣ",
        "Dark Mode" to "ਡਾਰਕ ਮੋਡ",
        "Printer Configuration" to "ਪ੍ਰਿੰਟਰ ਸੈਟਿੰਗਾਂ",
        "Save" to "ਸੁਰੱਖਿਅਤ ਕਰੋ",
        "Cancel" to "ਰੱਦ ਕਰੋ",
        "Add Customer" to "ਨਵਾਂ ਗਾਹਕ ਜੋੜੋ",
        "Select Language" to "ਭਾਸ਼ਾ ਚੁਣੋ",
        "Active" to "ਸਰਗਰਮ",
        "Inactive" to "ਨਿਸ਼ਕਿਰਿਆ",
        "Morning" to "ਸਵੇਰ",
        "Evening" to "ਸ਼ਾਮ",
        "Cow" to "ਗਾਂ",
        "Buffalo" to "ਮੱਝ",
        "Rate Chart" to "ਰੇਟ ਚਾਰਟ",
        "Connected" to "ਕਨੈਕਟਡ",
        "Not Connected" to "ਕਨੈਕਟ ਨਹੀਂ ਹੈ",
        "Print" to "ਪ੍ਰਿੰਟ",
        "Download PDF" to "ਪੀਡੀਐਫ ਡਾਊਨਲੋਡ",
        "Share on WhatsApp" to "ਵਟਸਐਪ ਤੇ ਸਾਂਝਾ ਕਰੋ",
        "Send by email" to "ਈਮੇਲ ਰਾਹੀਂ ਭੇਜੋ",
        "Login" to "ਲੌਗਇਨ",
        "Register" to "ਰਜਿਸਟਰ ਕਰੋ",
        "Username" to "ਯੂਜ਼ਰਨੇਮ",
        "Password" to "ਪਾਸਵਰਡ",
        "Full Name" to "ਪੂਰਾ ਨਾਮ",
        "Phone" to "ਫ਼ੋਨ ਨੰਬਰ",
        "Email" to "ਈਮੇਲ",
        "Role" to "ਭੂਮਿਕਾ",
        "Remember Me" to "ਮੈਨੂੰ ਯਾਦ ਰੱਖੋ",
        "Don't have an account? Register" to "ਖਾਤਾ ਨਹੀਂ ਹੈ? ਰਜਿਸਟਰ ਕਰੋ",
        "Already have an account? Login" to "ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ? ਲੌਗਇਨ ਕਰੋ"
    )
    private val marathiTranslations = mapOf(
        "Dashboard" to "डॅशबोर्ड",
        "Collection" to "दूध संकलन",
        "Farmers" to "शेतकरी",
        "Products" to "उत्पादने",
        "POS Sales" to "विक्री",
        "Payments" to "देयके",
        "Expenses" to "खर्च",
        "Reports" to "अहवाल",
        "Settings" to "सेटिंग्ज",
        "Home" to "मुख्यपृष्ठ",
        "Collect" to "संकलन",
        "Sales" to "विक्री",
        "Language Preference" to "भाषा पसंती",
        "Dark Mode" to "डार्क मोड",
        "Printer Configuration" to "प्रिंटर सेटिंग्ज",
        "Save" to "सुरक्षित करा",
        "Cancel" to "रद्द करा",
        "Add Customer" to "नवीन ग्राहक जोडा",
        "Select Language" to "भाषा निवडा",
        "Active" to "सक्रिय",
        "Inactive" to "निष्क्रिय",
        "Morning" to "सकाळ",
        "Evening" to "संध्याकाळ",
        "Cow" to "गाय",
        "Buffalo" to "म्हैस",
        "Rate Chart" to "दर पत्रक",
        "Connected" to "कनेक्टेड",
        "Not Connected" to "कनेक्ट नाही",
        "Print" to "प्रिंट करा",
        "Download PDF" to "पीडीएफ डाउनलोड",
        "Share on WhatsApp" to "व्हॉट्सॲपवर शेअर करा",
        "Send by email" to "ईमेलने पाठवा",
        "Login" to "लॉगिन",
        "Register" to "नोंदणी करा",
        "Username" to "युजरनेम",
        "Password" to "पासवर्ड",
        "Full Name" to "पूर्ण नाव",
        "Phone" to "फोन नंबर",
        "Email" to "ईमेल",
        "Role" to "भूमिका",
        "Remember Me" to "मला लक्षात ठेवा",
        "Don't have an account? Register" to "खाते नाही? नोंदणी करा",
        "Already have an account? Login" to "आधीच खाते आहे? लॉगिन करा"
    )
}
